baseURL = "https://pepp.reviews/"
languageCode = "en-us"
title = "Pepp's Indie Game Reviews"
theme = "sanctum"
googleAnalytics = "UA-93948508-2"

[params]
    logo = ""
    footer = "I made this mess!"

[social]
    youtube = "peppage"
    twitter = "peppage"

[taxonomies]
    type = "types"
    game = "games"
    tag = "tags"

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = false
        respectDoNotTrack = true
        useSessionStorage = false
